### PR TITLE
Initial structure & example

### PR DESCRIPTION
**Pull request by pgarciacamou**
@ugiacoman, to give you a small boost.

1. I used `react-native-create-library` to create the file structure.
2. I also created a full example with `react-native init` that I modified the iOS files only.

The latest version of react-native-create-library (v1.1.0) include support for react-native versions v0.40+.

Feel free to fully modify what you want, hope this helps.

### CODE REVIEW

**Comment by ugiacoman** [comment]
@pgarciacamou Looks pretty great, thanks for the PR! I'll take a look at it soon and provide feedback :)

**Comment by sibelius** [comment]
+1

**Comment by augustolazaro** [comment]
+1

**Comment by pgarciacamou** [comment]
I'm closing this PR because it was stale, I will rebuild in the near future.

**Pull request closed without merging**
